#########################
## Sass Lint File
#########################
# Linter Options
rules:
  'no-mergeable-selectors': 1,
  'pseudo-element': 0,
  'no-ids': 0,
  'mixins-before-declarations':
    - 1
    -
      exclude: ['tablet', 'desktop']
  'no-duplicate-properties': 0,
  'no-vendor-prefixes': 0,
  'single-line-per-selector': 0,
  'class-name-format':
    - 0
    - allow-leading-underscore: true
      convention: hyphenatedbem

