#########################
## Sass Lint File
#########################
# Linter Options
rules:
  'no-mergeable-selectors': 1,
  'pseudo-element': 0,
  'no-ids': 0,
  'mixins-before-declarations': 0,
  'no-duplicate-properties': 0,
  'no-vendor-prefixes': 0,
  'single-line-per-selector': 0
